spring:
  datasource:
    url: jdbc:h2:./soturi

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    prefix: file:static/

springdoc:
  swagger-ui:
    tryItOutEnabled: true

server:
  forward-headers-strategy: framework
